services:
  system:
    image: system-img
    build:
      context: .
      dockerfile: system

  build:
    image: build-img
    build:
      context: .
      dockerfile: build
      args:
        SYSTEM_IMAGE: system-img
    depends_on:
      - system

  app:
    image: app-img
    build:
      context: .
      dockerfile: run
      args:
        BUILD_IMAGE: build-img
    depends_on:
      - build
    ports:
      - "8080:8080"
