services:
  mynginx:
    image: mynginx
    container_name: mynginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./html:/var/www/html
    # restart: unless-stopped
