error_log  /dev/stderr warn;
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    access_log /dev/stdout;

    server {
        listen 8080 default_server;
        listen [::]:8080 default_server;

        root /var/www/html;

        location = /index {}
    }
}
