services:
  mysql:
    image: mysql:9.6
    env_file:
      - ./react-spring-app/.env
    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s

  nginx-proxy:
    image: nginx:alpine
    ports:
      - "3000:3000"
    volumes:
      - ./proxy_nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      frontend:
        condition: service_started
      backend:
        condition: service_started

  frontend:
    build:
      context: ./react-spring-app/react-frontend/
      dockerfile: Dockerfile
    env_file:
      - ./react-spring-app/react-frontend/.env

  backend:
    build:
      context: ./react-spring-app/spring-backend/
      dockerfile: Dockerfile
    env_file:
      - ./react-spring-app/.env
    environment:
      - DB_HOST=mysql
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
