services:
  postgres2:
    image: postgres:16
    container_name: postgres2
    environment:
      POSTGRES_USER: boss
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: db0
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - my_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U boss -d db0"]
      interval: 2s
      timeout: 5s
      retries: 30

  migrate:
    image: postgres:16
    volumes:
      - ./migrations:/migrations
    environment:
      PGHOST: postgres2
      PGUSER: boss
      PGPASSWORD: "1234"
      PGDATABASE: db0
    command: ["psql", "-v", "ON_ERROR_STOP=1", "-f", "/migrations/01_init.sql"]
    depends_on:
      postgres2:
        condition: service_healthy
    networks:
      - my_net
    restart: "no"

  my-app:
    image: my-app
    container_name: my-app
    working_dir: /app
    volumes:
      - ./app:/app
    environment:
      POSTGRES_HOST: postgres2
      POSTGRES_USER: boss
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: db0
    command: ["sleep", "infinity"]
    depends_on:
      migrate:
        condition: service_completed_successfully
    networks:
      - my_net

networks:
  my_net:
    driver: bridge
